# Script to annotate intergenic mutations with promoter regions based on blastn of inferred TSS on Sa_MW2 (reference Prados, BMC Genomics 2016) using the internal reference as database

USAGE="Error! $0 takes one argument\\n
Usage: $0 <snippy intergenic directory>\\n
	$0 runs in a conda snippy environment"

if [ $# -eq 0 ]
then 
	echo -e $USAGE
	exit 1
fi

# Set variables
GROUP_DIR=$(readlink -e $1)
GROUP=$(basename $GROUP_DIR)
QUERY=$(readlink -e ~/saureus-general/ref-genomes/Sa_MW2/representative_promoter.fa)
BLAST=$(readlink -e ~/perl5/bin/run-blastn.sh)

# Initial statements
echo "This $0"
echo "This script annotates intergenic mutations generated by snippy with predicted promoters based on Prados, BMC Genomics"
echo "Annotating intergenic mutations in $GROUP"

# Get promoters regions on the internal reference
cp -r $GROUP_DIR .
cd $GROUP

cd reference

mkdir promoters
cd promoters
cp ../ref.fa .
$BLAST $QUERY ref.fa promoters_ref_blastn
~/perl5/bin/blast2bed.sh promoters_ref_blastn.tab
mv promoters_ref_blastn.bed ref.promoters.bed

cd ../../

# Intersect with intergenic snps
bedtools intersect -a reference/promoters/ref.promoters.bed -b snps.intergenic.bed -wa -wb > mutated_intergenic_promoters.bed

cd ..

# Final statements
echo "$0 done"
echo "You can find the annotated mutations in $GROUP/mutated_intergenic_promoters.bed"

